#version 330 core

in vec2 v_uv; // texture coordinates

uniform sampler2D u_texture; // texture uniform

out vec4 fragColor; // output color

void main()
{
    // by default the y values are upside down, this flips it
    vec2 uv_correct = vec2(v_uv.x, 1.0 - v_uv.y);

    // the bitmap generated by freetype only has one channel: red, which is used for opacity
    float alpha = texture(u_texture, uv_correct).r;
    // temp color
    fragColor = vec4(1.0, 0.8, 0.6, alpha);
}